version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_PASSWORD=mysuperpassword
    ports:
      - "5432:5432"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
volumes:
  db:
    driver: local
