run-db:
	docker run --name my_postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysuperpassword -e POSTGRES_DB=my_db -v ${PWD}/db_data:/var/lib/postgresql/data -d postgres

seed:
	curl --request POST --data '{  \
		"title": "iPhone 9", \
		"description": "An apple mobile which is nothing like apple", \
		"price": 549, \
		"discountPercentage": 12.96, \
		"rating": 4.69, \
		"stock": 94, \
		"brand": "Apple", \
		"category": "smartphones", \
		"thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg", \
		"images": [ \
			"https://i.dummyjson.com/data/products/1/1.jpg", \
			"https://i.dummyjson.com/data/products/1/2.jpg", \
			"https://i.dummyjson.com/data/products/1/3.jpg", \
			"https://i.dummyjson.com/data/products/1/4.jpg", \
			"https://i.dummyjson.com/data/products/1/thumbnail.jpg" \
		] \
		}' localhost:8000/create-product \
		-H "Content-Type: application/json" \

	curl --request POST --data '{  \
		"title": "iPhone 9", \
		"description": "An apple mobile which is nothing like apple", \
		"price": 549, \
		"discountPercentage": 12.96, \
		"rating": 4.69, \
		"stock": 94, \
		"brand": "Apple", \
		"category": "smartphones", \
		"thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg", \
		"images": [ \
			"https://i.dummyjson.com/data/products/1/1.jpg", \
			"https://i.dummyjson.com/data/products/1/2.jpg", \
			"https://i.dummyjson.com/data/products/1/3.jpg", \
			"https://i.dummyjson.com/data/products/1/4.jpg", \
			"https://i.dummyjson.com/data/products/1/thumbnail.jpg" \
		] \
		}' localhost:8000/create-product \
		-H "Content-Type: application/json" \

	curl --request POST --data '{  \
		"title": "iPhone 9", \
		"description": "An apple mobile which is nothing like apple", \
		"price": 549, \
		"discountPercentage": 12.96, \
		"rating": 4.69, \
		"stock": 94, \
		"brand": "Apple", \
		"category": "smartphones", \
		"thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg", \
		"images": [ \
			"https://i.dummyjson.com/data/products/1/1.jpg", \
			"https://i.dummyjson.com/data/products/1/2.jpg", \
			"https://i.dummyjson.com/data/products/1/3.jpg", \
			"https://i.dummyjson.com/data/products/1/4.jpg", \
			"https://i.dummyjson.com/data/products/1/thumbnail.jpg" \
		] \
		}' localhost:8000/create-product \
		-H "Content-Type: application/json" \

	curl --request POST --data '{  \
		"title": "iPhone 9", \
		"description": "An apple mobile which is nothing like apple", \
		"price": 549, \
		"discountPercentage": 12.96, \
		"rating": 4.69, \
		"stock": 94, \
		"brand": "Apple", \
		"category": "smartphones", \
		"thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg", \
		"images": [ \
			"https://i.dummyjson.com/data/products/1/1.jpg", \
			"https://i.dummyjson.com/data/products/1/2.jpg", \
			"https://i.dummyjson.com/data/products/1/3.jpg", \
			"https://i.dummyjson.com/data/products/1/4.jpg", \
			"https://i.dummyjson.com/data/products/1/thumbnail.jpg" \
		] \
		}' localhost:8000/create-product \
		-H "Content-Type: application/json" \

	curl --request POST --data '{  \
		"title": "iPhone 9", \
		"description": "An apple mobile which is nothing like apple", \
		"price": 549, \
		"discountPercentage": 12.96, \
		"rating": 4.69, \
		"stock": 94, \
		"brand": "Apple", \
		"category": "smartphones", \
		"thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg", \
		"images": [ \
			"https://i.dummyjson.com/data/products/1/1.jpg", \
			"https://i.dummyjson.com/data/products/1/2.jpg", \
			"https://i.dummyjson.com/data/products/1/3.jpg", \
			"https://i.dummyjson.com/data/products/1/4.jpg", \
			"https://i.dummyjson.com/data/products/1/thumbnail.jpg" \
		] \
		}' localhost:8000/create-product \
		-H "Content-Type: application/json" \

	curl --request POST --data '{  \
		"title": "iPhone 9", \
		"description": "An apple mobile which is nothing like apple", \
		"price": 549, \
		"discountPercentage": 12.96, \
		"rating": 4.69, \
		"stock": 94, \
		"brand": "Apple", \
		"category": "smartphones", \
		"thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg", \
		"images": [ \
			"https://i.dummyjson.com/data/products/1/1.jpg", \
			"https://i.dummyjson.com/data/products/1/2.jpg", \
			"https://i.dummyjson.com/data/products/1/3.jpg", \
			"https://i.dummyjson.com/data/products/1/4.jpg", \
			"https://i.dummyjson.com/data/products/1/thumbnail.jpg" \
		] \
		}' localhost:8000/create-product \
		-H "Content-Type: application/json" \

	curl --request POST --data '{  \
		"title": "iPhone 9", \
		"description": "An apple mobile which is nothing like apple", \
		"price": 549, \
		"discountPercentage": 12.96, \
		"rating": 4.69, \
		"stock": 94, \
		"brand": "Apple", \
		"category": "smartphones", \
		"thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg", \
		"images": [ \
			"https://i.dummyjson.com/data/products/1/1.jpg", \
			"https://i.dummyjson.com/data/products/1/2.jpg", \
			"https://i.dummyjson.com/data/products/1/3.jpg", \
			"https://i.dummyjson.com/data/products/1/4.jpg", \
			"https://i.dummyjson.com/data/products/1/thumbnail.jpg" \
		] \
		}' localhost:8000/create-product \
		-H "Content-Type: application/json" \